CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto Increment ID',
  DEVICE_CODE varchar(100) NOT NULL COMMENT 'Device Code',
  UNIT_SEQ int(10) unsigned NOT NULL COMMENT 'Unit Sequence Number',
  CHANNEL_SEQ bigint(10) unsigned NOT NULL COMMENT 'Channel Sequence Number',
  CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Channel Name',
  OWNER_CODE varchar(255) DEFAULT NULL COMMENT 'Belonging Organization Code',
  OWNER_NAME varchar(100) DEFAULT NULL COMMENT 'Belonging Organization Name',
  CARD_NUMBER varchar(100) DEFAULT NULL COMMENT 'Access Card Number',
  SWIPE_TIME datetime DEFAULT NULL COMMENT 'Card Swipe Time',
  SWIPE_TIME_UTC bigint(20) DEFAULT NULL COMMENT 'Card Swipe Time (Milliseconds)',
  SWIPE_ID varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Personnel ID',
  PICTURE1 varchar(255) DEFAULT NULL COMMENT 'Captured Image 1',
  PICTURE2 varchar(255) DEFAULT NULL COMMENT 'Captured Image 2',
  PICTURE3 varchar(255) DEFAULT NULL COMMENT 'Captured Image 3',
  PICTURE4 varchar(255) DEFAULT NULL COMMENT 'Captured Image 4',
  MEMO varchar(255) DEFAULT NULL COMMENT 'Description',
  CARD_TYPE varchar(2) DEFAULT NULL COMMENT 'Card Type',
  ENTEROREXIT tinyint(3) DEFAULT NULL COMMENT 'Entry/Exit Status',
  OPEN_TYPE int(11) DEFAULT NULL COMMENT 'Door Open Type and Elevator Control Event Type',
  DEVICE_TYPE tinyint(3) DEFAULT NULL COMMENT 'Device Type',
  ALARM_CODE varchar(100) DEFAULT NULL COMMENT 'Alarm Code',
  FIRST_NAME varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'First Name',
  LAST_NAME varchar(255) DEFAULT NULL COMMENT 'Last Name',
  ZH_NAME varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Chinese Name',
  EN_NAME varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'English Name',
  TEL varchar(100) DEFAULT NULL COMMENT 'Phone Number',
  GENDER tinyint(3) DEFAULT NULL COMMENT 'Gender',
  IDENTIFICATION_NUM varchar(100) DEFAULT NULL COMMENT 'Identification Number',
  CHANNEL_ID varchar(100) DEFAULT NULL COMMENT 'Channel Code',
  DEVICE_NAME varchar(100) DEFAULT NULL COMMENT 'Device Name',
  STAGE_ID varchar(10) DEFAULT NULL COMMENT 'Stage ID',
  BUILDING_ID varchar(10) DEFAULT NULL COMMENT 'Building ID',
  UNIT_ID varchar(10) DEFAULT NULL COMMENT 'Unit ID',
  ROOM_ID varchar(100) DEFAULT NULL COMMENT 'Room Number',
  ROOM_NUMBER varchar(100) DEFAULT NULL COMMENT 'Room Long Number, Stage#Building#Unit#Room',
  RECORD_SOURCE tinyint(3) unsigned DEFAULT 0 COMMENT 'Record Source, 0 for Access Control Event, 1 for Elevator Control Event',
  AREA_CODE varchar(100) DEFAULT NULL COMMENT 'Area Code',
  AREA_NAME varchar(100) DEFAULT NULL COMMENT 'Area Name',
  POINT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Access Control Point ID',
  POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Access Control Point Name',
  POINT_TYPE tinyint(3) DEFAULT NULL COMMENT 'Point Type, 1=Access Control, 2=Elevator Control, 3=Turnstile',
  OPEN_TYPE_LEVEL tinyint(3) DEFAULT NULL COMMENT 'Event Type, 1=Normal, 2=Abnormal, 3=Alarm',
  CREATE_TIME timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Entry Time',
  PRIMARY KEY (ID),
  KEY IDX_DOOR_ALARM_CODE (ALARM_CODE),
  KEY IDX_DOOR_SWIPE_TIME_UTC (SWIPE_TIME_UTC),
  KEY IDX_DOOR_ACCESS_CHANNEL_TIME_UTC (CHANNEL_ID,SWIPE_TIME_UTC),
  KEY IDX_DOOR_SWIPEID_SWIPETIMEUTC (SWIPE_ID,SWIPE_TIME_UTC),
  KEY IDX_DOOR_ACCESS_TYPE_TIME_UTC (OPEN_TYPE_LEVEL,SWIPE_TIME_UTC),
  KEY IDX_DOOR_AREA_CODE_SWIPE_TIME_UTC (AREA_CODE,SWIPE_TIME_UTC),
  KEY IDX_DOOR_POINT_ID_SWIPE_TIME_UTC (POINT_ID,SWIPE_TIME_UTC)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Access Control Records';
