CREATE TABLE oseadb.{table_name} (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  CODE varchar(50) NOT NULL COMMENT 'Personnel capture information ID, controlled by upper-level business, unique key, corresponds to the ID in the recognition information table',
  DEVICE_CODE varchar(50) NOT NULL COMMENT 'Device code',
  CHANNEL_SEQ bigint(12) unsigned NOT NULL COMMENT 'Channel ID',
  CHANNEL_ID varchar(50) NOT NULL COMMENT 'Channel ID',
  FACE_IMAGE_URL varchar(200) DEFAULT NULL COMMENT 'Face image URL',
  PICTURE_URL varchar(200) DEFAULT NULL COMMENT 'Scene image URL',
  APPEAR_TIME tinyint(4) unsigned DEFAULT NULL COMMENT 'Appearance count',
  AGE tinyint(3) unsigned DEFAULT NULL COMMENT 'Age',
  GENDER tinyint(3) unsigned DEFAULT NULL COMMENT 'Gender',
  FRINGE tinyint(3) unsigned DEFAULT NULL COMMENT 'Fringe, 0 = No, 1 = Yes',
  EYE tinyint(3) unsigned DEFAULT NULL COMMENT 'Eye status: 1 = Unrecognized, 2 = Closed, 3 = Open',
  MOUTH tinyint(3) unsigned DEFAULT NULL COMMENT 'Mouth status: 1 = Unrecognized, 2 = Closed, 3 = Open',
  MASK tinyint(3) unsigned DEFAULT NULL COMMENT 'Mask status: 1 = Unrecognized, 2 = No mask, 3 = Mask worn',
  BEARD tinyint(3) unsigned DEFAULT NULL COMMENT 'Beard status: 1 = Unrecognized, 2 = No beard, 3 = Beard',
  GLASSES tinyint(3) unsigned DEFAULT NULL COMMENT 'Glasses status: 0 = No, 1 = Glasses, 2 = Sunglasses',
  EMOTION tinyint(3) DEFAULT NULL COMMENT 'Emotion: -1 = Unrecognized, 0 = Smile, 1 = Angry, 2 = Sad, 3 = Disgusted, 4 = Fear, 5 = Surprise, 6 = Normal, 7 = Laughing, 8 = Happy, 9 = Confused, 10 = Screaming',
  BEGIN_TIME datetime DEFAULT NULL COMMENT 'Start time',
  END_TIME datetime DEFAULT NULL COMMENT 'End time',
  CREATE_TIME datetime NOT NULL COMMENT 'Entry time',
  ALARM_CODE varchar(500) DEFAULT NULL COMMENT 'Alarm code',
  PRIMARY KEY (ID),
  KEY IDX_FACE_DETECTION_ID (CODE),
  KEY IDX_FACE_DETECTION_DEVICE_CODE (DEVICE_CODE),
  KEY IDX_FACE_DETECTION_BEGIN_TIME (BEGIN_TIME),
  KEY IDX_FACE_DETECTION_CHANNEL_ID_BEGIN_TIME_UNION (CHANNEL_ID, BEGIN_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Personnel capture information';
