CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key ID',
  DEVICE_CODE varchar(50) NOT NULL COMMENT 'Device code',
  DEVICE_NAME varchar(50) DEFAULT NULL COMMENT 'Device name',
  CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Channel ID',
  CHANNEL_NAME varchar(50) DEFAULT NULL COMMENT 'Channel name',
  USER_ID bigint(20) unsigned DEFAULT NULL COMMENT 'MPT user ID',
  USER_NAME varchar(50) DEFAULT NULL COMMENT 'MPT user name',
  FILE_ID varchar(50) NOT NULL COMMENT 'Unique file identifier',
  FILE_NAME varchar(100) NOT NULL COMMENT 'File name',
  FILE_URL varchar(255) DEFAULT NULL COMMENT 'File storage path',
  FILE_TYPE tinyint(3) DEFAULT NULL COMMENT 'File type: 0=Unknown, 1=Video, 2=Audio, 3=Image',
  FILE_LENGTH bigint(20) DEFAULT NULL COMMENT 'File size (in bytes)',
  FILE_START_TIME bigint(20) DEFAULT NULL COMMENT 'File start time (UTC)',
  FILE_END_TIME bigint(20) DEFAULT NULL COMMENT 'File end time (UTC)',
  FILE_TIME_LENGTH int(11) DEFAULT NULL COMMENT 'File duration',
  CREATE_TIME datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Record creation time',
  SOUTCE_TYPE tinyint(3) unsigned DEFAULT NULL COMMENT 'Source type, 1=MPT, 2=EEC device',
  EEC_DEVICE_CODE varchar(50) DEFAULT NULL COMMENT 'EEC device code',
  FILE_LENGTH_OFF bigint(20) DEFAULT 0 COMMENT 'Download location',
  COLLECT_TIME bigint(20) DEFAULT NULL COMMENT 'Data collection time (UTC timestamp in seconds)',
  PRIMARY KEY (ID),
  KEY IDX_MPT_RECORD_START_TIME (FILE_START_TIME),
  KEY IDX_MPT_RECORD_DEVICE_CODE (DEVICE_CODE),
  KEY IDX_MPT_RECORD_UNION (FILE_ID, EEC_DEVICE_CODE)
) ENGINE=InnoDB AUTO_INCREMENT=2024110000000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='MPT law enforcement record table';
