CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment ID',
  DEVICE_CODE varchar(50) NOT NULL COMMENT 'Device code',
  UNIT_SEQ int(10) unsigned NOT NULL COMMENT 'Unit sequence number',
  CHANNEL_SEQ int(5) NOT NULL COMMENT 'Channel sequence number',
  RECORD_TIME datetime DEFAULT NULL COMMENT 'Record time (accurate to hour)',
  ENTERED_SUBTOTAL int(5) DEFAULT 0 COMMENT 'Number of people entered',
  EXITED_SUBTOTAL int(5) DEFAULT 0 COMMENT 'Number of people exited',
  PASSED_SUBTOTAL int(10) DEFAULT 0 COMMENT 'Number of people passed',
  MEMO varchar(255) DEFAULT NULL COMMENT 'Remarks',
  STAT int(2) DEFAULT 0 COMMENT 'Record status',
  PC_FLAG tinyint(3) unsigned DEFAULT 0 COMMENT 'People flow statistic type: 1=Region, 2=Entrance/Exit, 3=Gate',
  PER_HOUR_TEMPERATURE int(10) unsigned DEFAULT NULL COMMENT 'Hourly temperature (Fahrenheit)',
  PER_HOUR_WEATHER int(10) unsigned DEFAULT NULL COMMENT 'Hourly weather',
  WEATHER int(10) unsigned DEFAULT NULL COMMENT 'All-day weather',
  MALE_TOTAL1 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 1-10',
  FEMALE_TOTAL1 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 1-10',
  MALE_TOTAL2 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 11-20',
  FEMALE_TOTAL2 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 11-20',
  MALE_TOTAL3 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 21-30',
  FEMALE_TOTAL3 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 21-30',
  MALE_TOTAL4 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 31-40',
  FEMALE_TOTAL4 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 31-40',
  MALE_TOTAL5 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 41-50',
  FEMALE_TOTAL5 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 41-50',
  MALE_TOTAL6 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 51-60',
  FEMALE_TOTAL6 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 51-60',
  MALE_TOTAL7 int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 61-70',
  FEMALE_TOTAL7 int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 61-70',
  MALE_TOTAL_OTHER int(5) unsigned DEFAULT 0 COMMENT 'Number of males aged 71 and above',
  FEMALE_TOTAL_OTHER int(5) unsigned DEFAULT 0 COMMENT 'Number of females aged 71 and above',
  SMILE_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people smiling',
  ANGER_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people angry',
  SADNESS_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people sad',
  HATE_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people disgusted',
  FEAR_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people scared',
  SURPRISE_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people surprised',
  NORMAL_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of normal people',
  LAUGH_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people laughing',
  HAPPY_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of happy people',
  PUZZLED_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of puzzled people',
  SCREAM_TOTAL int(5) unsigned DEFAULT 0 COMMENT 'Number of people screaming',
  DEVICE_RULE_CODE varchar(50) DEFAULT NULL COMMENT 'Rule ID on the device',
  RECORD_TIME_UTC bigint(20) unsigned NOT NULL COMMENT 'Start time of the day (milliseconds)',
  CREATE_TIME bigint(20) unsigned DEFAULT NULL COMMENT 'Record creation time (milliseconds)',
  PRIMARY KEY (ID),
  KEY IDX_PEOPLE_FLOW_ECORD_TIME (RECORD_TIME),
  KEY IDX_PEOPLE_FLOW_HRECORD_TIME_UTC (RECORD_TIME_UTC)
) ENGINE=InnoDB AUTO_INCREMENT=2024110000000000711 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='People flow statistics table';
