CREATE TABLE oseadb.{table_name} (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  CODE varchar(50) NOT NULL COMMENT 'Personnel capture information ID, controlled by upper-level business, unique key, corresponds to ID in the recognition information table',
  U_ID bigint(20) unsigned NOT NULL COMMENT 'Platform personnel ID',
  FACE_IMAGE_URL varchar(200) DEFAULT NULL COMMENT 'Face image avatar',
  PERSON_NAME varchar(255) NOT NULL COMMENT 'Name',
  PERSON_TYPE_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Personnel type ID',
  PERSON_TYPE_NAME varchar(50) DEFAULT NULL COMMENT 'Personnel type name',
  PERSON_ID varchar(50) DEFAULT NULL COMMENT 'ID',
  GENDER tinyint(3) NOT NULL COMMENT 'Gender',
  AGE tinyint(3) unsigned DEFAULT NULL COMMENT 'Age',
  BIRTHDAY date DEFAULT NULL COMMENT 'Birthday',
  NATIONALITY varchar(50) DEFAULT NULL COMMENT 'Nationality',
  MEMO varchar(255) DEFAULT NULL COMMENT 'Personnel information description',
  REPOSITORY_ID bigint(20) unsigned NOT NULL COMMENT 'Platform face library ID',
  REPOSITORY_NAME varchar(50) NOT NULL COMMENT 'Face library name',
  REPOSITORY_COLOR varchar(10) NOT NULL COMMENT 'Face library color',
  SIMILARITY tinyint(3) unsigned DEFAULT NULL COMMENT 'Similarity',
  SURVEILLANCE tinyint(3) DEFAULT NULL COMMENT 'Surveillance status, 0 = Not under surveillance, 1 = Under surveillance',
  BEGIN_TIME bigint(20) NOT NULL COMMENT 'Start time',
  END_TIME bigint(20) DEFAULT NULL COMMENT 'End time',
  CREATE_TIME datetime NOT NULL COMMENT 'Entry time',
  ALARM_CODE varchar(50) DEFAULT NULL COMMENT 'Alarm code',
  FRINGE tinyint(3) unsigned DEFAULT NULL COMMENT 'Fringe, 0 = No, 1 = Yes',
  EYE tinyint(3) unsigned DEFAULT NULL COMMENT '1 = Not recognized, 2 = Closed eyes, 3 = Open eyes',
  MOUTH tinyint(3) unsigned DEFAULT NULL COMMENT '1 = Not recognized, 2 = Closed mouth, 3 = Open mouth',
  MASK tinyint(3) unsigned DEFAULT NULL COMMENT '1 = Not recognized, 2 = No mask, 3 = Wearing a mask',
  BEARD tinyint(3) unsigned DEFAULT NULL COMMENT '1 = Not recognized, 2 = No beard, 3 = Has beard',
  GLASSES tinyint(3) unsigned DEFAULT NULL COMMENT 'Glasses, 0 = No, 1 = Glasses, 2 = Sunglasses',
  EMOTION tinyint(3) DEFAULT NULL COMMENT 'Emotion, -1 = Not recognized, 0 = Smile, 1 = Anger, 2 = Sadness, 3 = Disgust, 4 = Fear, 5 = Surprise, 6 = Normal, 7 = Laughter, 8 = Happiness, 9 = Confusion, 10 = Scream',
  PERSON_TYPE_ALARM_CODE varchar(50) DEFAULT NULL COMMENT 'Personnel type alarm code',
  DEVICE_CODE varchar(50) NOT NULL COMMENT 'Device code',
  CHANNEL_ID varchar(50) NOT NULL COMMENT 'Channel ID',
  PICTURE_URL varchar(200) DEFAULT NULL COMMENT 'Scene picture',
  PERSON_FACE_IMAGE_URL varchar(200) DEFAULT NULL COMMENT 'Personnel face image',
  CHANNEL_NAME varchar(50) DEFAULT NULL COMMENT 'Channel name',
  PRIMARY KEY (ID),
  KEY IDX_ADM_FACE_RECOGNITION_ALARM_CODE (ALARM_CODE),
  KEY IDX_FACE_RECOGNITION_BEGIN_TIME_CHANNEL_ID_UNION (BEGIN_TIME, CHANNEL_ID),
  KEY IDX_PERSON_TYPE_ALARM_CODE (PERSON_TYPE_ALARM_CODE),
  KEY IDX_FACE_RECOGNITION_BEGIN_TIME (BEGIN_TIME),
  KEY IDX_FACE_DETECT_PERSON_ID (U_ID)
) ENGINE=InnoDB AUTO_INCREMENT=2024070500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Personnel recognition information -- the original table is no longer maintained';
