CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment ID',
  EVENT smallint(5) unsigned NOT NULL COMMENT 'System event',
  CONTENT varchar(255) DEFAULT NULL COMMENT 'Event content',
  CREATE_DATE datetime DEFAULT NULL COMMENT 'Creation date',
  CREATE_TIME_UTC bigint(20) DEFAULT NULL COMMENT 'Creation time UTC',
  RESOURCE_CODE varchar(50) DEFAULT NULL COMMENT 'Resource code',
  RESOURCE_NAME varchar(50) DEFAULT NULL COMMENT 'Resource name',
  PRIMARY KEY (ID),
  KEY IDX_LOG_SYSTEM_CREATE_DATE_UTC_EVENT (CREATE_TIME_UTC, EVENT)
) ENGINE=InnoDB AUTO_INCREMENT=2024110000000000069 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
