CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  DEV_ID varchar(50) NOT NULL COMMENT 'Device ID',
  DEV_CHNNUM int(11) NOT NULL COMMENT 'Channel number',
  DEV_NAME varchar(50) NOT NULL COMMENT 'Device name',
  DEV_CHNNAME varchar(50) NOT NULL COMMENT 'Channel name',
  CAR_NUM varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'License plate number',
  EXT_CAR_NUM varchar(100) DEFAULT NULL COMMENT 'Extended license plate number',
  CAR_NUM_LENGTH varchar(100) DEFAULT NULL COMMENT 'License plate length',
  CAR_NUM_AREA_CODE varchar(100) DEFAULT NULL COMMENT 'License plate area code',
  ISSUE_PLACE varchar(100) DEFAULT NULL COMMENT 'Issuing place',
  CAR_NUMTYPE int(11) NOT NULL COMMENT 'License plate type',
  CAR_NUMCOLOR int(11) NOT NULL COMMENT 'License plate color',
  CAR_SPEED int(11) DEFAULT NULL COMMENT 'Car speed',
  CAR_TYPE int(11) NOT NULL COMMENT 'Vehicle type',
  CAR_COLOR int(11) NOT NULL COMMENT 'Vehicle color',
  CAR_LENGTH int(11) NOT NULL COMMENT 'Vehicle length',
  CAR_DIRECT varchar(8) NOT NULL COMMENT 'Driving direction',
  CAR_WAY_CODE varchar(8) NOT NULL COMMENT 'Lane code',
  CAP_TIME int(11) DEFAULT NULL COMMENT 'Capture time',
  CAP_DATE datetime NOT NULL COMMENT 'Capture date',
  INF_NOTE varchar(255) DEFAULT NULL COMMENT 'Information note',
  MAX_SPEED int(11) DEFAULT NULL COMMENT 'Maximum speed limit',
  MIN_SPEED int(11) DEFAULT NULL COMMENT 'Minimum speed limit',
  CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  CAR_IMG1_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  CAR_IMG2_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  CAR_IMG3_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  CAR_IMG4_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  CAR_IMG5_URL varchar(255) DEFAULT NULL COMMENT 'Image storage path',
  REC_STAT tinyint(4) DEFAULT 0 COMMENT 'Record status',
  DEV_CHNID varchar(50) NOT NULL COMMENT 'Device channel ID',
  CAR_IMG_COUNT int(11) DEFAULT NULL COMMENT 'Number of images',
  SAVE_FLAG tinyint(4) DEFAULT 0 COMMENT 'Whether to permanently save images',
  DC_CLEANFLAG tinyint(4) DEFAULT 0 COMMENT 'Flag for whether image is cleared by DATACLEAN program',
  PIC_ID int(11) DEFAULT NULL COMMENT 'Image group ID',
  CAR_IMG_PLATE_TOP int(11) DEFAULT NULL COMMENT 'License plate coordinates: TOP',
  CAR_IMG_PLATE_LEFT int(11) DEFAULT NULL COMMENT 'License plate coordinates: LEFT',
  CAR_IMG_PLATE_BOTTOM int(11) DEFAULT NULL COMMENT 'License plate coordinates: BOTTOM',
  CAR_IMG_PLATE_RIGHT int(11) DEFAULT NULL COMMENT 'License plate coordinates: RIGHT',
  CAR_BRAND int(11) DEFAULT NULL COMMENT 'Car brand',
  ISSAFETYBELT tinyint(4) DEFAULT 0 COMMENT 'Whether seatbelt is fastened',
  ISVISOR tinyint(4) DEFAULT 0 COMMENT 'Whether there is a sun visor',
  BIND_STAT tinyint(4) DEFAULT 0 COMMENT 'Whether the image is synthesized',
  CAR_NUM_PIC varchar(255) DEFAULT NULL COMMENT 'Small license plate image URL',
  COMBINED_PIC_URL varchar(255) DEFAULT NULL COMMENT 'Synthesis image storage path URL',
  VERIFY_MEMO varchar(255) DEFAULT NULL COMMENT 'Verification information during vehicle capture',
  CAR_WIDTH int(11) DEFAULT NULL COMMENT 'Vehicle width (cm)',
  CAR_HEIGHT int(11) DEFAULT NULL COMMENT 'Vehicle height (cm)',
  SERVICE_CODE varchar(20) NOT NULL DEFAULT '0' COMMENT 'Toll station server number',
  REC_TYPE int(11) DEFAULT NULL COMMENT 'Violation type',
  PIC_RECORD_IDX varchar(60) DEFAULT NULL,
  CROSSROAD_ID varchar(30) DEFAULT NULL,
  CHAN_CODE varchar(30) DEFAULT NULL,
  DATA_SOURCE tinyint(4) DEFAULT NULL COMMENT 'Data source: 0,1 - Toll Station; 2 - Extracted from real-time; 3 - Extracted from recording; 4 - Extracted from file; 5 - Extracted from UVSS',
  CREATE_TIME timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Entry time',
  REC_CODE varchar(32) DEFAULT NULL COMMENT 'Violation code',
  VIDEO_URL varchar(255) DEFAULT NULL COMMENT 'Video URL',
  CAP_DAY date DEFAULT NULL COMMENT 'Capture day',
  CAP_DATE_UTC bigint(20) DEFAULT NULL COMMENT 'Capture date UTC',
  IN_VEHICLE_GROUP tinyint(2) NOT NULL DEFAULT 0 COMMENT 'Whether the vehicle is in the database: 0 = No, 1 = Yes',
  PRIMARY KEY (ID),
  KEY IDX_CP_COMBINE_UTC (CAR_NUM, CAP_DATE_UTC),
  KEY IDX_PICRECORD_DEVCHNID_UTC (DEV_CHNID, CAP_DATE_UTC),
  KEY IDX_CP_CAP_DATE_UTC (CAP_DATE_UTC),
  KEY IDX_CPIC_BRAND_CD_UTC (CAR_BRAND, CAP_DATE_UTC),
  KEY IDX_CPIC_BRAND_COLOR_UTC (CAR_BRAND, CAR_COLOR, CAP_DATE_UTC),
  KEY IDX_CPIC_BRAND_DEV (CAR_BRAND, DEV_CHNID),
  KEY IDX_CPIC_BRAND_COLOR_DEV (CAR_BRAND, CAR_COLOR, DEV_CHNID),
  KEY IDX_CPIC_COLOR_DEV_UTC (CAR_COLOR, DEV_CHNID, CAP_DATE_UTC),
  KEY IDX_CAR_TYPE_CAP_DATE_UTC (CAR_TYPE, CAP_DATE_UTC),
  KEY IDX_IN_GROUP_CAP_DATE_UTC (IN_VEHICLE_GROUP, CAP_DATE_UTC)
) ENGINE=InnoDB AUTO_INCREMENT=2024092900000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Suspicious vehicle capture table';
