CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
  CAR_NUM varchar(50) NOT NULL COMMENT 'Car Plate Number',
  ORIGINAL_CAR_NUM varchar(50) DEFAULT NULL COMMENT 'Original Car Plate Number',
  EXT_CAR_NUM varchar(100) DEFAULT NULL COMMENT 'Extended Car Plate Number',
  CAR_NUM_LENGTH varchar(100) DEFAULT NULL COMMENT 'Car Plate Length',
  CAR_NUM_AREA_CODE varchar(100) DEFAULT NULL COMMENT 'Car Plate Area Code',
  CAR_NUM_TYPE int(11) DEFAULT NULL COMMENT 'Car Plate Type',
  ISSUE_PLACE varchar(100) DEFAULT NULL COMMENT 'Place of Issue',
  IS_FUZZY_MATCHED tinyint(2) NOT NULL DEFAULT 0 COMMENT 'Fuzzy Match: 1-Yes, 0-No',
  ACCESS_AUTHORITY tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Access Authority: 1=Allow Access, 2=Prohibited, 3=Verify Access',
  CAR_COLOR int(3) unsigned DEFAULT NULL COMMENT 'Car Color',
  CAR_BRAND int(4) DEFAULT NULL COMMENT 'Car Brand',
  CAR_MODEL int(10) DEFAULT 0 COMMENT 'Car Model',
  OWNER_NAME_ZH varchar(255) DEFAULT NULL COMMENT 'Owner Name in Chinese',
  OWNER_NAME_EN varchar(255) DEFAULT NULL COMMENT 'Owner Name in English',
  ORG_CODE varchar(255) DEFAULT NULL COMMENT 'Organization Code',
  ORG_NAME varchar(255) DEFAULT NULL COMMENT 'Organization Name',
  COMPANY varchar(100) DEFAULT NULL COMMENT 'Company Name',
  CARD_OWNER_ID varchar(100) DEFAULT NULL COMMENT 'Card Owner ID',
  CARD_OWNER_NAME varchar(255) DEFAULT NULL COMMENT 'Card Owner Name',
  CARD_NUMBER varchar(100) DEFAULT NULL COMMENT 'Card Number',
  CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Main Camera Channel ID',
  CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Main Camera Channel Name',
  EXTEND_CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Auxiliary Camera Channel ID',
  EXTEND_CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Auxiliary Camera Channel Name',
  PARKING_LOT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Parking Lot ID',
  PARKING_LOT_NAME varchar(100) DEFAULT NULL COMMENT 'Parking Lot Name',
  ENTER_TIME bigint(20) unsigned NOT NULL COMMENT 'Entry Time, in milliseconds',
  EXIT_TIME bigint(20) unsigned NOT NULL COMMENT 'Exit Time, in milliseconds',
  CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Car Image URL',
  CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Car Plate Image URL',
  EXT_CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Auxiliary Car Image URL',
  EXT_CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Auxiliary Car Plate Image URL',
  MATCH_FLAG tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Main Recognition Source: 0=Auxiliary Camera Image, 1=Main Camera Image',
  CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Vehicle Capture Record ID',
  EXT_CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Auxiliary Camera Vehicle Capture Record ID',
  ENTER_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry Record ID',
  OPERATOR_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Force Exit Operator ID',
  POINT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Gate ID',
  POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Gate Name',
  POSITION_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Position ID',
  POSITION_NAME varchar(100) DEFAULT NULL COMMENT 'Position Name',
  RELEASE_RULE varchar(200) DEFAULT NULL COMMENT 'Release Rule',
  GROUP_IDS varchar(1000) DEFAULT NULL COMMENT 'Vehicle Entry/Exit Group ID, separated by semicolons',
  GROUP_NAMES varchar(2000) DEFAULT NULL COMMENT 'Vehicle Entry/Exit Group Name, separated by commas',
  ALARM_STATUS tinyint(2) NOT NULL DEFAULT 0 COMMENT 'Vehicle Scan Status: 0=Not Scanned, 1=Scanned',
  PRIMARY KEY (ID),
  KEY IDX_FORCE_EXIT_RECORD_CAR_NUM (CAR_NUM),
  KEY IDX_FORCE_EXIT_RECORD_ENTER_TIME (ENTER_TIME),
  KEY IDX_FORCE_EXIT_RECORD_EXIT_TIME (EXIT_TIME)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Force Vehicle Exit Record Table';
