CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
  CAR_NUM varchar(50) NOT NULL COMMENT 'License plate number',
  ORIGINAL_CAR_NUM varchar(50) DEFAULT NULL COMMENT 'Original license plate number',
  EXT_CAR_NUM varchar(100) DEFAULT NULL COMMENT 'Extended license plate number',
  CAR_NUM_LENGTH varchar(100) DEFAULT NULL COMMENT 'License plate length',
  CAR_NUM_AREA_CODE varchar(100) DEFAULT NULL COMMENT 'License plate area code',
  CAR_NUM_TYPE int(11) DEFAULT NULL COMMENT 'License plate type',
  ISSUE_PLACE varchar(100) DEFAULT NULL COMMENT 'Issuing place',
  IS_FUZZY_MATCHED tinyint(2) NOT NULL DEFAULT 0 COMMENT 'Fuzzy match: 1-Yes, 0-No',
  ACCESS_AUTHORITY tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Access authority: 1-Allow, 2-Deny, 3-Validate',
  CAR_COLOR int(3) unsigned DEFAULT NULL COMMENT 'Car color',
  CAR_BRAND int(4) DEFAULT NULL COMMENT 'Car brand',
  CAR_MODEL int(10) DEFAULT 0 COMMENT 'Car model',
  OWNER_NAME_ZH varchar(255) DEFAULT NULL COMMENT 'Owner name (Chinese)',
  OWNER_NAME_EN varchar(255) DEFAULT NULL COMMENT 'Owner name (English)',
  ORG_CODE varchar(255) DEFAULT NULL COMMENT 'Organization code',
  ORG_NAME varchar(255) DEFAULT NULL COMMENT 'Organization name',
  COMPANY varchar(100) DEFAULT NULL COMMENT 'Company name',
  CARD_OWNER_ID varchar(100) DEFAULT NULL COMMENT 'Card owner ID',
  CARD_OWNER_NAME varchar(255) DEFAULT NULL COMMENT 'Card owner name',
  CARD_NUMBER varchar(100) DEFAULT NULL COMMENT 'Card number',
  CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Main camera channel ID',
  CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Main camera channel name',
  EXTEND_CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Secondary camera channel ID',
  EXTEND_CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Secondary camera channel name',
  PARKING_LOT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Parking lot ID',
  PARKING_LOT_NAME varchar(100) DEFAULT NULL COMMENT 'Parking lot name',
  EXIT_TIME bigint(20) unsigned NOT NULL COMMENT 'Exit time, in milliseconds',
  EXIT_DATE datetime NOT NULL COMMENT 'Exit date and time',
  CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Car image URL',
  CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'License plate image URL',
  EXT_CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Secondary camera car image URL',
  EXT_CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Secondary camera license plate image URL',
  CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Vehicle capture record ID',
  EXT_CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Secondary camera capture record ID',
  MATCH_FLAG tinyint(2) unsigned DEFAULT 1 COMMENT 'Main recognition info: 0-Secondary camera, 1-Main camera',
  IS_NEED_COUNT tinyint(2) unsigned DEFAULT 1 COMMENT 'Need count of available spaces: 0-No, 1-Yes',
  ENTER_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry record ID',
  POINT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Gate ID',
  POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Gate name',
  POSITION_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Position ID',
  POSITION_NAME varchar(100) DEFAULT NULL COMMENT 'Position name',
  RELEASE_RULE varchar(200) DEFAULT NULL COMMENT 'Release rule',
  GROUP_IDS varchar(1000) DEFAULT NULL COMMENT 'Vehicle entry/exit group IDs, separated by semicolons',
  GROUP_NAMES varchar(2000) DEFAULT NULL COMMENT 'Vehicle entry/exit group names, separated by commas',
  PRIMARY KEY (ID),
  KEY IDX_EXIT_RECORD_CAR_NUM (CAR_NUM),
  KEY IDX_EXIT_RECORD_EXIT_TIME (EXIT_TIME)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Vehicle exit record table';
