CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment ID',
  CAR_NUM varchar(50) DEFAULT NULL COMMENT 'Car plate number (used for exit record if only removed, otherwise used for entry record)',
  CAR_COLOR int(10) DEFAULT NULL COMMENT 'Captured car body color during entry',
  CAR_BRAND int(10) DEFAULT NULL COMMENT 'Captured vehicle brand during entry',
  OWNER_NAME_ZH varchar(200) DEFAULT NULL COMMENT 'Owner name in Chinese',
  OWNER_NAME_EN varchar(200) DEFAULT NULL COMMENT 'Owner name in English',
  ORG_CODE varchar(255) DEFAULT NULL COMMENT 'Personnel group code',
  ORG_NAME varchar(255) DEFAULT NULL COMMENT 'Personnel group name',
  COMPANY varchar(100) DEFAULT NULL COMMENT 'Company name',
  PARKING_LOT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Parking lot ID',
  PARKING_LOT_NAME varchar(100) DEFAULT NULL COMMENT 'Parking lot name',
  ENTER_POSITION_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry position ID',
  ENTER_POSITION_NAME varchar(100) DEFAULT NULL COMMENT 'Entry position name',
  ENTER_POINT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry gate point ID',
  ENTER_POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Entry gate point name',
  CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Channel ID',
  CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Channel name',
  DEVICE_CODE varchar(50) DEFAULT NULL COMMENT 'Vehicle detection device code',
  DEVICE_NAME varchar(100) DEFAULT NULL COMMENT 'Vehicle detection device name',
  SPACE_ID varchar(50) NOT NULL COMMENT 'Parking space ID',
  SPACE_NAME varchar(100) DEFAULT NULL COMMENT 'Parking space name (space number)',
  ENTER_TIME datetime DEFAULT NULL COMMENT 'Entry time',
  ENTER_TIME_UTC bigint(20) unsigned DEFAULT NULL COMMENT 'Entry time in milliseconds',
  ENTER_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Path to entry vehicle body image',
  ENTER_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Path to entry vehicle plate image',
  ENTER_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry record ID / Forced exit record ID (linked to entry record table)',
  RELATION_FLAG tinyint(2) DEFAULT 1 COMMENT 'Relation type: 1 = linked to entry record, 2 = linked to forced exit record',
  ENTER_CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry vehicle capture record ID (linked to capture table)',
  GROUP_IDS varchar(1000) DEFAULT NULL COMMENT 'Vehicle entry/exit group IDs, separated by colon; visitor cars = -1',
  GROUP_NAMES varchar(2000) DEFAULT NULL COMMENT 'Vehicle entry/exit group names, separated by comma',
  EXIT_CAR_NUM varchar(50) DEFAULT NULL COMMENT 'Exit car plate number',
  EXIT_TIME datetime DEFAULT NULL COMMENT 'Exit time',
  EXIT_TIME_UTC bigint(20) unsigned DEFAULT NULL COMMENT 'Exit time in milliseconds',
  EXIT_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Path to exit vehicle body image',
  EXIT_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Path to exit vehicle plate image',
  EXIT_CAPTURE_RECORD_ID bigint(20) DEFAULT NULL COMMENT 'Exit vehicle capture record ID (linked to capture table)',
  PRIMARY KEY (ID),
  KEY IDX_PARKING_RECORD_CAR_NUM (CAR_NUM),
  KEY IDX_PARKING_RECORD_ENTER_TIME (ENTER_TIME_UTC),
  KEY IDX_PARKING_RECORD_EXIT_TIME (EXIT_TIME_UTC)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Parking record table';
