CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
  CAR_NUM varchar(50) NOT NULL COMMENT 'License Plate Number',
  ORIGINAL_CAR_NUM varchar(50) DEFAULT NULL COMMENT 'Original License Plate',
  EXT_CAR_NUM varchar(100) DEFAULT NULL COMMENT 'Extended License Plate',
  CAR_NUM_LENGTH varchar(100) DEFAULT NULL COMMENT 'License Plate Length',
  CAR_NUM_AREA_CODE varchar(100) DEFAULT NULL COMMENT 'License Plate Area Code',
  CAR_NUM_TYPE int(11) DEFAULT NULL COMMENT 'License Plate Type',
  ISSUE_PLACE varchar(100) DEFAULT NULL COMMENT 'Issuing Place',
  IS_FUZZY_MATCHED tinyint(2) NOT NULL DEFAULT 0 COMMENT 'Fuzzy Match Status: 1-Yes, 0-No',
  ACCESS_AUTHORITY tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Access Authority: 1=Allow Access, 2=Prohibit Access, 3=Verify Access',
  CAR_COLOR int(3) unsigned DEFAULT NULL COMMENT 'Car Color',
  CAR_BRAND int(4) DEFAULT NULL COMMENT 'Car Brand',
  CAR_MODEL int(10) DEFAULT 0 COMMENT 'Car Model',
  OWNER_NAME_ZH varchar(255) DEFAULT NULL COMMENT 'Owner Name (Chinese)',
  OWNER_NAME_EN varchar(255) DEFAULT NULL COMMENT 'Owner Name (English)',
  ORG_CODE varchar(255) DEFAULT NULL COMMENT 'Organization Code',
  ORG_NAME varchar(255) DEFAULT NULL COMMENT 'Organization Name',
  COMPANY varchar(100) DEFAULT NULL COMMENT 'Company Name',
  CARD_OWNER_ID varchar(100) DEFAULT NULL COMMENT 'Card Holder ID',
  CARD_OWNER_NAME varchar(255) DEFAULT NULL COMMENT 'Card Holder Name',
  CARD_NUMBER varchar(100) DEFAULT NULL COMMENT 'Card Number',
  CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Main Camera Channel ID',
  CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Main Camera Channel Name',
  EXTEND_CHANNEL_ID varchar(50) DEFAULT NULL COMMENT 'Auxiliary Camera Channel ID',
  EXTEND_CHANNEL_NAME varchar(100) DEFAULT NULL COMMENT 'Auxiliary Camera Channel Name',
  PARKING_LOT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Parking Lot ID',
  PARKING_LOT_NAME varchar(100) DEFAULT NULL COMMENT 'Parking Lot Name',
  ENTER_TIME bigint(20) unsigned NOT NULL COMMENT 'Enter Time (milliseconds)',
  ENTER_DATE datetime NOT NULL COMMENT 'Enter Date and Time',
  CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Image URL',
  CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'License Plate Image URL',
  EXT_CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Auxiliary Camera Image URL',
  EXT_CAR_NUM_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Auxiliary Camera License Plate Image URL',
  CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Capture Record ID',
  EXT_CAPTURE_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Auxiliary Camera Capture Record ID',
  MATCH_FLAG tinyint(2) unsigned DEFAULT 1 COMMENT 'Main Recognition Source: 0=Auxiliary Camera Image, 1=Main Camera Image',
  IS_NEED_COUNT tinyint(2) unsigned DEFAULT 1 COMMENT 'Need to Count Remaining Spots: 0-No, 1-Yes',
  EXIT_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Exit Record ID',
  FORCE_EXIT_RECORD_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Forced Exit Record ID',
  STATUS tinyint(2) unsigned NOT NULL COMMENT 'Vehicle Status: 1-Exited, 2-Not Exited, 3=Forced Exit',
  POINT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Gate ID',
  POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Gate Name',
  POSITION_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Position ID',
  POSITION_NAME varchar(100) DEFAULT NULL COMMENT 'Position Name',
  RELEASE_RULE varchar(200) DEFAULT NULL COMMENT 'Release Rule',
  GROUP_IDS varchar(1000) DEFAULT NULL COMMENT 'Vehicle Access Group ID, separated by semicolon',
  GROUP_NAMES varchar(2000) DEFAULT NULL COMMENT 'Vehicle Access Group Names, separated by comma',
  PRIMARY KEY (ID),
  KEY IDX_ENTER_RECORD_CAR_NUM (CAR_NUM),
  KEY IDX_ENTER_RECORD_ENTER_TIME (ENTER_TIME)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Vehicle Entry Record Table';
