CREATE TABLE oseadb.{table_name} (
  ID bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  DEV_ID varchar(50) NOT NULL COMMENT 'Device ID',
  DEV_CHNID varchar(50) NOT NULL COMMENT 'Device Channel ID',
  DEV_CHNNUM int(5) NOT NULL COMMENT 'Channel Number',
  DEV_NAME varchar(100) DEFAULT NULL COMMENT 'Device Name',
  DEV_CHNNAME varchar(100) DEFAULT NULL COMMENT 'Channel Name',
  CAR_OWNER_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Car Owner ID',
  OWNER_NAME_ZH varchar(200) DEFAULT NULL COMMENT 'Owner Name in Chinese',
  OWNER_NAME_EN varchar(200) DEFAULT NULL COMMENT 'Owner Name in English',
  DEPARTMENT_ID varchar(255) DEFAULT NULL COMMENT 'Department ID',
  COMPANY_NAME varchar(100) DEFAULT NULL COMMENT 'Company Name',
  CAR_NUM varchar(50) NOT NULL COMMENT 'Car Plate Number',
  EXT_CAR_NUM varchar(100) DEFAULT NULL COMMENT 'Extended Car Plate Number',
  CAR_NUM_LENGTH varchar(100) DEFAULT NULL COMMENT 'Car Plate Length',
  CAR_NUM_AREA_CODE varchar(100) DEFAULT NULL COMMENT 'Car Plate Area Code',
  ISSUE_PLACE varchar(100) DEFAULT NULL COMMENT 'Issue Place',
  CAR_NUMTYPE int(3) DEFAULT NULL COMMENT 'Car Plate Type',
  CAR_NUMCOLOR int(3) DEFAULT NULL COMMENT 'Car Plate Color',
  CAR_SPEED int(3) DEFAULT NULL COMMENT 'Car Speed',
  CAR_TYPE tinyint(2) unsigned DEFAULT 0 COMMENT 'Car Type: 0=Visitor, 1=Blacklist, 2=No Group, 3=Regular Car, 4=VIP',
  CAR_COLOR int(3) DEFAULT NULL COMMENT 'Car Color',
  CAR_LENGTH int(4) DEFAULT NULL COMMENT 'Car Length',
  CAR_DIRECT varchar(8) NOT NULL COMMENT 'Car Direction',
  CAR_WAY_CODE varchar(8) DEFAULT NULL COMMENT 'Lane Number',
  CAR_BRAND int(4) DEFAULT NULL COMMENT 'Car Brand',
  CAR_MODEL int(10) DEFAULT 0 COMMENT 'Car Model',
  CAP_TIME datetime NOT NULL COMMENT 'Capture Time',
  CAP_TIME_UTC bigint(20) DEFAULT NULL COMMENT 'Capture Time in UTC (milliseconds)',
  INF_NOTE varchar(255) DEFAULT NULL COMMENT 'Information Notes',
  MAX_SPEED int(3) DEFAULT NULL COMMENT 'Maximum Speed Limit',
  MIN_SPEED int(3) DEFAULT NULL COMMENT 'Minimum Speed Limit',
  CAR_IMG_URL varchar(255) DEFAULT NULL COMMENT 'Image Storage Path',
  CAR_NUM_PIC varchar(255) DEFAULT NULL COMMENT 'Car Plate Small Image URL',
  REC_STAT int(2) DEFAULT 0 COMMENT 'Record Status',
  SAVE_FLAG int(1) DEFAULT 0 COMMENT 'Flag for Permanent Image Saving',
  DC_CLEANFLAG int(1) DEFAULT 0 COMMENT 'Data Clean Flag (used by DATACLEAN program)',
  IMG_PLATE varchar(100) DEFAULT NULL COMMENT 'Plate Coordinates in Image (Top, Right, Bottom, Left)',
  VERIFY_MEMO varchar(255) DEFAULT NULL COMMENT 'Verification Memo for Car Capture Info',
  CAR_INNER_CATEGORY varchar(10) DEFAULT NULL COMMENT 'Car Entry/Exit Category (see dictionary)',
  PARKING_LOT_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Parking Lot ID',
  ENTER_ID bigint(20) unsigned DEFAULT NULL COMMENT 'Entry Capture ID',
  PARKING_LOT_NAME varchar(100) DEFAULT NULL COMMENT 'Parking Lot Name',
  POINT_NAME varchar(100) DEFAULT NULL COMMENT 'Gate Name',
  POSITION_NAME varchar(100) DEFAULT NULL COMMENT 'Position Name',
  ORG_NAME varchar(255) DEFAULT NULL COMMENT 'Organization Name',
  GROUP_IDS varchar(1000) DEFAULT NULL COMMENT 'Vehicle Entry/Exit Group IDs, separated by semicolons',
  GROUP_NAMES varchar(2000) DEFAULT NULL COMMENT 'Vehicle Entry/Exit Group Names, separated by commas',
  DATA_FLAG tinyint(2) NOT NULL DEFAULT 1 COMMENT 'Data Source: 1=ITC Capture, 2=Vehicle Detector Capture',
  PRIMARY KEY (ID),
  KEY IDX_CAR_CAPTURE_CAP_TIME_UTC (CAP_TIME_UTC),
  KEY IDX_CAR_CAPTURE_CAR_NUM_CAP_TIME_UTC (CAR_NUM, CAP_TIME_UTC),
  KEY IDX_CAR_CAPTURE_CHANNEL_CAP_TIME_UTC (DEV_CHNID, CAP_TIME_UTC)
) ENGINE=InnoDB AUTO_INCREMENT=2024112500000000001 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Vehicle Entry/Exit Capture Table';
